server:
  port: 8080

spring:
  application:
    name: Device Service

  datasource:
    url: jdbc:postgresql://localhost:5432/devices_db
    username: admin
    password: ggD3v1c3
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: device-rating-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: localhost
      port: 6379
      password: ggD3v1c3

  cache:
    type: redis

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: ggD3v1c3
  bucket: images

logging:
  level:
    vadim: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      access: unrestricted
