server:
  port: 8080

spring:
  application:
    name: Device Service

  datasource:
    url: jdbc:postgresql://postgres:5432/devices_db
    username: admin
    password: ggD3v1c3
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 60000
      leak-detection-threshold: 15000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000

minio:
  endpoint: http://minio:9000
  accessKey: admin
  secretKey: ggD3v1c3
  bucket: images
