spring:
  application:
    name: Device Service

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DEVICE_SERVICE_DB_USERNAME}  # Используем переменную окружения
    password: ${DEVICE_SERVICE_DB_PASSWORD}  # Используем переменную окружения
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 60000  # Рекомендуется добавить для стабильности
      leak-detection-threshold: 15000  # Для поиска утечек соединений

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  data:
    web:
      sort:
        sort-parameter: LOWER_CASE
    redis:
      host: localhost
      port: 6379
      timeout: 2000

logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
        data.redis: DEBUG
        security: DEBUG  # Добавление логирования для безопасности
      hibernate:
        SQL: DEBUG
        type.descriptor.sql: TRACE

server:
  port: 8080
