services:
  postgres:
    image: postgres:latest
    container_name: device_service_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ggD3v1c3
      POSTGRES_DB: devices_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: device_service_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: device_service_minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: ggD3v1c3
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
